PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.12.10
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.12.10.62109-Setup.exe
    InstallerSha256: 10818E2173CE5AC37B85E7DC85E37ECDBC8197DA10583186C30C6AA181226186
    ElevationRequirement: elevatesSelf
    ProductCode: "{0ee169ba7650fe41e76c83531a34506ae9f258dd_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
