PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 10.6.14
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-10.6.14.45742-Setup.exe
    InstallerSha256: 8B289F177DBDF81FF9E4E0777D7FB48284A1168E325F0516E68551260024FF18
    ElevationRequirement: elevatesSelf
    ProductCode: "{6f6244868d19eb075ba8393bfba55391e9294be6_is1}"
  - Architecture: x64
    InstallerType: exe
    Scope: user
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-10.6.14.45742-User-x64-Setup.exe
    InstallerSha256: CEF2F4AEF42973BE778F85EC45D97B2383EE1C31EC62EEFF5230C4CD9A52D23F
    ProductCode: "{6f6244868d19eb075ba8393bfba55391e9294be6_is1}"
  - Architecture: arm64
    InstallerType: exe
    Scope: user
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-10.6.14.45742-User-arm64-Setup.exe
    InstallerSha256: E03281F088966EA1AA30865145F2949570ED3B39E0FAEB9982058047C5177B62
    ProductCode: "{6f6244868d19eb075ba8393bfba55391e9294be6_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
