PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 11.6.0
InstallModes:
  - interactive
  - silent
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-11.6.0-Setup.exe
    InstallerSha256: 8E619C28DCFFA2245530CF0A101F8EB5EA32077666E4CBDEA1DDD24B234D0374
    ElevationRequirement: elevatesSelf
    ProductCode: "{MENDIX-STUDIO-PRO-11-6-0-PLACEHOLDER}"
  - Architecture: x64
    InstallerType: exe
    Scope: user
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-11.6.0-User-x64-Setup.exe
    InstallerSha256: 5E9904CC480879876CF9CE963DB6A39631C50C8F7F0DE08EFD43E51C03271AF0
    ProductCode: "{MENDIX-STUDIO-PRO-11-6-0-PLACEHOLDER}"
  - Architecture: arm64
    InstallerType: exe
    Scope: user
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-11.6.0-User-arm64-Setup.exe
    InstallerSha256: 24091899D87B105F43CB09611E66C0D648C226A66284E8FF0C56575DE82D927E
    ProductCode: "{MENDIX-STUDIO-PRO-11-6-0-PLACEHOLDER}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestVersion: 1.4.0
