PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.12.14
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.12.14.5695-Setup.exe
    InstallerSha256: E0FB5EC4C8F7A1E705014D529C7973E9120BEB4792DA85891BB2CF59F0B2C8CE
    ElevationRequirement: elevatesSelf
    ProductCode: "{9509fe18b4c4ed44cf881ce073a6347e34b03f04_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
