PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.18.4
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.18.4.62522-Setup.exe
    InstallerSha256: 6434051BF6649742613A97A9394A7EE780DF81AE334BF23D0F6A25E09507D136
    ElevationRequirement: elevatesSelf
    ProductCode: "{bfc467fa054f4ec9a980e88109b761c6e20ae7a3_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
