PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.6.4
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.6.4.33791-Setup.exe
    InstallerSha256: 081718E9FEF0EE7659E0F10959317A0E62C8A583194D9942F041541C27965265
    ElevationRequirement: elevatesSelf
    ProductCode: "{dddbc156f153d8ddabba1a865ff38ef5d8f1c7da_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
