PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.6.12
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.6.12.46216-Setup.exe
    InstallerSha256: 948D08DC193C77DF74C57F0206A80ECCF919C26289EAB3B9282ACDEB77183DE7
    ElevationRequirement: elevatesSelf
    ProductCode: "{475bd28d3d1761ed528bc56f03f3445fc5646a98_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
