PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.3.0
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.3.0.22930-Setup.exe
    InstallerSha256: 13091D128D1F8CB0488C412E79B82F7A5E22F5D0A2882F1A9C986888F6307381
    ElevationRequirement: elevatesSelf
    ProductCode: "{9ba2e765e0ff89f5bcfebb798f23203250a12cd6_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
