PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.6.7
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.6.7.35942-Setup.exe
    InstallerSha256: 27615BBD1B7CF64E947BAD4A446DB305DA4990EE49240AD32B39C17F110C3DFD
    ElevationRequirement: elevatesSelf
    ProductCode: "{058b34b3022ba291646f13b90706f71b3db624df_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
