PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.18.2
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.18.2.55931-Setup.exe
    InstallerSha256: D6B8E6E4E96844A72FBDC824439F85A0405EA3CC744E662A9E54501F18DCC979
    ElevationRequirement: elevatesSelf
    ProductCode: "{83dd999f1e14970b675ff4aff7038bd5b6af97b8_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
