PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 10.12.5
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-10.12.5.45892-Setup.exe
    InstallerSha256: E4301CAB221CF905046F51E3E29C66DC03A8F2479487B3A98D44BEB78C04E378
    ElevationRequirement: elevatesSelf
    ProductCode: "{8bc778a2b92f15232206fd19fef1098939629560_is1}"
  - Architecture: x64
    InstallerType: exe
    Scope: user
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-10.12.5.45892-User-x64-Setup.exe
    InstallerSha256: 8BD97E76D71EA7301F6F52E3D0AB70F8D4D8D5EFA47C3C10F81F8057AA007982
    ProductCode: "{8bc778a2b92f15232206fd19fef1098939629560_is1}"
  - Architecture: arm64
    InstallerType: exe
    Scope: user
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-10.12.5.45892-User-arm64-Setup.exe
    InstallerSha256: E1310F0B13B4F00E1A940D453437944A1E74AC7A682808DCF5C6A01440B91B20
    ProductCode: "{8bc778a2b92f15232206fd19fef1098939629560_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
