PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.12.7
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.12.7.54456-Setup.exe
    InstallerSha256: F1EBF23F93B167903624993B21A7571F522CAC1BF72A5B093329EB8F33FB8272
    ElevationRequirement: elevatesSelf
    ProductCode: "{0c84c749cbd4ed4d546d789e5e18ab214cebf0da_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
