PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.14.1
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.14.1.46860-Setup.exe
    InstallerSha256: 6A8BD25C8B937A4C94DBCE3B5ACB7A9A3314E5E3F1F192655262765623ADD153
    ElevationRequirement: elevatesSelf
    ProductCode: "{335ebcefda185e543e4c773b9d1518a2d8226ee8_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
