PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.18.3
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.18.3.58938-Setup.exe
    InstallerSha256: 18B27C2EBDDA13D9B63D093919C0A76932EB00D5FBE2A0636D18361DCDDD2B28
    ElevationRequirement: elevatesSelf
    ProductCode: "{18e90e37285d92a2e413aded1db46f384dcdde45_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
