PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.22.0
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.22.0.62233-Setup.exe
    InstallerSha256: E0B4357CF240C99486252498FE916253728564C61EC55C34CF2C4E3A0FC393B9
    ElevationRequirement: elevatesSelf
    ProductCode: "{77a937f20c5d4d0cceed6bffb9d8a53644605223_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
