PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.12.2
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.12.2.44241-Setup.exe
    InstallerSha256: FB61E1D0C4312D056908E11A897162BA38A13CEC545922AD5485B7CCFD0AA1B8
    ElevationRequirement: elevatesSelf
    ProductCode: "{ab0542ca76f2411edb6e080ae33fd7baffb69a20_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
