PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.0.5
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.0.5.17836-Setup.exe
    InstallerSha256: 0AAB42EB7B96C45C64AA099EF4C18C7780E6BE88BFE713C475CDAD0800DD287E
    ElevationRequirement: elevatesSelf
    ProductCode: "{4d615b7723cd14e0b6739f622c641a6ae458ae6e_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
