PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.18.5
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.18.5.3736-Setup.exe
    InstallerSha256: ADD599813CDF97E5361E4E1EC39D98BE71956B9CBC7A6C1280A688FB5890DE41
    ElevationRequirement: elevatesSelf
    ProductCode: "{afabcd3c27c7da0e501158c516d1497f30a10a06_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
