PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.12.3
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.12.3.46747-Setup.exe
    InstallerSha256: 37B2A5C308778C8F0F4635547C60C5270C03C3C931F86F651357A4E61817ABE9
    ElevationRequirement: elevatesSelf
    ProductCode: "{5d75153ec7b711da072213038c7e4d770158b29e_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
