PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.21.0
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.21.0.59661-Setup.exe
    InstallerSha256: 3AAE12ADBEF985EB5F74A6253D94F78C96C8A5A44F76B208808E64E9F147DDFC
    ElevationRequirement: elevatesSelf
    ProductCode: "{2c727b817e4277c2033421d4ff7be98c7961e852_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
