PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.14.2
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.14.2.48548-Setup.exe
    InstallerSha256: 64B214274BCA005B8D7159133A7F55FFFBDCE50764374F42EBC0B4084D2548C9
    ElevationRequirement: elevatesSelf
    ProductCode: "{f8f24314c49be0ee53144fe3cd5af45003ea2b60_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
