PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.15.0
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.15.0.47426-Setup.exe
    InstallerSha256: F1CB2441F6B270B2CBD5C9EDB6216A52998BB69EB505E323500DC0B979ACBED7
    ElevationRequirement: elevatesSelf
    ProductCode: "{e0f12161551d197adde002e37e4daf1b9e84f1cf_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
