PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.18.6
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.18.6.4600-Setup.exe
    InstallerSha256: 5A3F021771E505C84664526D4DBC884EF8056DCCA80F40AEF72E3C2E4F3EF662
    ElevationRequirement: elevatesSelf
    ProductCode: "{56d0bfc349e04852f7944ea0489db5381942dee3_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
