PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.10.2
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.10.2.39379-Setup.exe
    InstallerSha256: 5A639018F9EDD41FE285B242D123A63F9CBB0334D63CDEECE28744ECCD884B98
    ElevationRequirement: elevatesSelf
    ProductCode: "{d49dc3dabb8de799b9591b736f70443e24d15f7c_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
