PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.10.1
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.10.1.37625-Setup.exe
    InstallerSha256: 7F1539E33D7C938C4A027477B0924F290D922AF80555CE5A6DA3E953DFB38BA8
    ElevationRequirement: elevatesSelf
    ProductCode: "{fe894e100e2a3d72ff11c3b07983db7b7e219f60_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
