PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.12.12
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.12.12.4599-Setup.exe
    InstallerSha256: 3C9F99D7C3F9D0823E2E370E75726FAE15DF5CA75F3975BC295A2EF57A82515A
    ElevationRequirement: elevatesSelf
    ProductCode: "{ab3b76ee501b6ea1cf83e8496b9abe039a3959e4_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
