PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.6.5
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.6.5.34071-Setup.exe
    InstallerSha256: 4B61015A52C9B217F3644A9A1E42AF6EA6EA846D673BA73AC3242362DA311B88
    ElevationRequirement: elevatesSelf
    ProductCode: "{4b8e731da565829b29660a62785591cf558d4acd_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
