PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.6.1
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.6.1.29396-Setup.exe
    InstallerSha256: 6737D29F7F05107D69FBC4589BD7D0765DD22ACCEB013BA1FD3522F4EAA3F246
    ElevationRequirement: elevatesSelf
    ProductCode: "{9ac8515fcefab678229982d889f9fede3af8a09a_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
