PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.4.0
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.4.0.24572-Setup.exe
    InstallerSha256: E148C1B50164F63EF1C815D53BFA762180F22C5924BE3DA9CC29D8CC48AFAC9B
    ElevationRequirement: elevatesSelf
    ProductCode: "{4f936efaf0036c9b94c29a7dae924738be87463f_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
