PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.17.1
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.17.1.52718-Setup.exe
    InstallerSha256: E633FC8005CB3610AF18D49C580B15286DC6BDAAF82AFD781049A79CE2172CE6
    ElevationRequirement: elevatesSelf
    ProductCode: "{4424c1dd7a5f006a96661420554c14d3b741a530_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
