PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.2.0
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.2.0.20531-Setup.exe
    InstallerSha256: F2F36B0A1D4D0D94104B07B286F39D555F689ACF75E7ECEB65629C918A974238
    ElevationRequirement: elevatesSelf
    ProductCode: "{dd2f8c59e572ff4fc667de8151727a129fc870a2_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
