PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.6.10
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.6.10.40529-Setup.exe
    InstallerSha256: FEC897CA202FE0AA4178AC603D873F7133A309A3F084CDC7AFC208FFBD24709A
    ElevationRequirement: elevatesSelf
    ProductCode: "{999714346752ffc2c2aec622465be87e87878037_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
