PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.8.0
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.8.0.32026-Setup.exe
    InstallerSha256: 9E978354FBA2DECEFA0D81DE26051DAC27ABF7C2A61301F3DBA78E158417C30A
    ElevationRequirement: elevatesSelf
    ProductCode: "{adf90c94d90cc4387a866cb01525cb685686dcbd_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
