PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.13.1
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.13.1.45479-Setup.exe
    InstallerSha256: 8099617BD99DD7476A85B75B98F6204C158B7EAFC587918A11DBC82B06D5B00A
    ElevationRequirement: elevatesSelf
    ProductCode: "{18e69173688cee423776dfe3bbc5c923c0d30ea8_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
