PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.6.11
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.6.11.42323-Setup.exe
    InstallerSha256: EC1BCF0747974CD302D03396900A5D50C9903199EB981A9679652648EFCF0182
    ElevationRequirement: elevatesSelf
    ProductCode: "{8be8c9a594f444f71d6cef6c3aca115a4002c354_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
