PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.12.11
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.12.11.3830-Setup.exe
    InstallerSha256: EC4822396B06A0F637BEBCA23CCEBAA3FA98298DC3B9B90F3E353354D43A3088
    ElevationRequirement: elevatesSelf
    ProductCode: "{f8c7770f65b6cedd7d5756c6409d9bf3edcc628b_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
