PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.12.13
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.12.13.5158-Setup.exe
    InstallerSha256: 83953ACE2DF9830FF5CE44C2FC540903A9C654C5115A0E77D23AD4461C9A7027
    ElevationRequirement: elevatesSelf
    ProductCode: "{3b484f1a723d49952be3994edbd0aa06be5dfb4c_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
