PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.12.9
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.12.9.61773-Setup.exe
    InstallerSha256: A3442F619713A7E67C91006C08AF1A247CB424E46644E1B3B52AEC73960954C9
    ElevationRequirement: elevatesSelf
    ProductCode: "{dfb7ff94debf382915fb6a58174d558d499f7c75_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
