PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.12.1
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.12.1.42381-Setup.exe
    InstallerSha256: 3F1ACD21BDB82001A4A17B657E720AAFD9D9BFE105F748438091DF8D456DE689
    ElevationRequirement: elevatesSelf
    ProductCode: "{2d021d2c87503c212e7db77c62273d099496f581_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
