PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.6.3
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.6.3.32292-Setup.exe
    InstallerSha256: 5A23DF9F1E75758BCC4AB88BF2A4AAFB9CD15094947E9F53B7442EE841A18A4C
    ElevationRequirement: elevatesSelf
    ProductCode: "{db2297d6083f25065de3e10dc8b67681b84f9be2_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
