PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.16.1
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.16.1.50105-Setup.exe
    InstallerSha256: 1EAEDFEA4D82A31ED5CA242296AABF14F949230E93F4C70E191B2996B146290A
    ElevationRequirement: elevatesSelf
    ProductCode: "{cc460d85666dc1cb91927bd270a8e60c76d6a255_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
