PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.6.9
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.6.9.38960-Setup.exe
    InstallerSha256: 707430F6D2B6E803803CC85A703BC6F2B55C575B1C7ECAB942C8B1D88DF93F19
    ElevationRequirement: elevatesSelf
    ProductCode: "{a19234746fdcb3bb1e2aaa80b85add4becf48eab_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
