PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.5.1
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.5.1.27523-Setup.exe
    InstallerSha256: F2B85FD6E6ED177892F6FB50C7AC0D620EB1EC7F0093B8E407F319CD5515F220
    ElevationRequirement: elevatesSelf
    ProductCode: "{32fe74011308d681cf3331ffb99806cd506cd137_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
