PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.5.0
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.5.0.25874-Setup.exe
    InstallerSha256: B87BBBEEF0F49FA17C5CF216E6B1D9C87D09D835CA106049D3F3CB93D4BDDE1B
    ElevationRequirement: elevatesSelf
    ProductCode: "{661e41ae112ed565749568cfd93637960929cfb7_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
