PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.10.0
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.10.0.36429-Setup.exe
    InstallerSha256: C4CAA8645AEC2200DDF88496C74434836C185E81B4F52BAF50607729979D8C0F
    ElevationRequirement: elevatesSelf
    ProductCode: "{05e49e2dbaa6367ddd203f705eee1724fa4a52e6_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
