PackageIdentifier: Mendix.MendixStudioPro
PackageVersion: 9.6.2
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
Installers:
  - Architecture: x64
    InstallerType: exe
    Scope: machine
    InstallerUrl: https://artifacts.rnd.mendix.com/modelers/Mendix-9.6.2.30227-Setup.exe
    InstallerSha256: DF70084AB9858FFC20391BA7266D751F2B34D72BF968A3FA392B544A8999C7B4
    ElevationRequirement: elevatesSelf
    ProductCode: "{7c1972ad215e0a0a24f4204781377bc4e8f74276_is1}"
InstallationNotes: "Multiple versions can be installed side-by-side."
ManifestType: installer
ManifestVersion: 1.6.0
